version = 3
final_space = true

[palette]
  blue = '#8CAAEE'
  closer = 'p:os'
  lavender = '#BABBF1'
  os = '#ACB0BE'
  pink = '#F4B8E4'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:os'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  newline = false
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}p:os{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = false

  [[blocks.segments]]
    template = '{{ .Icon }} '
    foreground = 'p:os'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .UserName }}@{{ .HostName }} '
    foreground = 'p:blue'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = ''
      home_icon = ''
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '{{ .HEAD }} '
    foreground = 'p:lavender'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      cherry_pick_icon = ''
      commit_icon = ''
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ''
      no_commits_icon = ''
      rebase_icon = ''
      revert_icon = ''
      tag_icon = ''

  [[blocks.segments]]
    template = '{{ .FormattedMs }} '
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}p:os{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
